HH:MM:SS time formatting bug in crc-interactive
pitt-crc/wrappers pull request #214
Opened 2023-09-11 12:02 UTC by yassinkhalifa

It seems when entering the decimal value for the parameter "-t" or "--time" in crc-interactive it's formatted in the srun_dict as "{}:00" which makes it interpreted as "MM:SS" but if using the string format "01:00" and it's formatted in the srun_dict as "{}:00" then it's interpreted as "HH:MM:SS" which is the necessary format for "srun". I added a possible fix, please take a look and feel free to discard it and fix it in any other way because I am sure this is not the best way to fix it, I was just trying to expose where the error comes from.

2023-09-11 13:41 UTC, djperrefort commented on apps/crc_interactive.py
> +                datetime.strptime(args.time, '%H:%M:%S').minute / 3600)
I think this should be `datetime.strptime(args.time, '%H:%M:%S').seconds`:

```python
            datetime_obj = datetime.strptime(args.time, '%H:%M:%S')
            check_time = datetime_obj.hour + datetime_obj.minute / 60 + datetime_obj.second / 3600
```

2023-09-11 13:51 UTC, yassinkhalifa commented
I totally agree that users don't really need the seconds part in time. If you want, I can just change that back to how it was before and just leave the decimal formatting line that I added (just modify it to be HH:MM which will be amended with seconds in srun_dict).

2023-09-11 13:56 UTC, djperrefort commented
Sounds good to me.

2023-09-11 14:11 UTC, yassinkhalifa commented
That's done now!

2023-09-11 14:30 UTC, djperrefort reviewed
I'd prefer to avoid mutating arguments to a function call, particularly a validation function. It violates the principle of least astonishment and can cause unexpected behavior down the line.

Proposition:

Why don't we move the time parsing logic into the commandline parser itself. We can define a top level function like:

```python
def parse_time(time_str: str) -> time:
    try:
        return time(*time_str.split(':'))

    except Exception:
        raise ArgumentTypeError(f'Could not parse time value {time_str}')
```

and have it cast automatically as follows:

```python
resource_args.add_argument('-t', '--time', type=parse_time, ...)
```

This makes life easier later in the code. Validation becomes much shorter:

```python
        check_time = args.time.hour + args.time.minute / 60
        if not self.min_time <= check_time <= self.max_time:
            ...
```

The only missing piece is updating the `create_srun_command` method to handle the new argument type. That should be fairly straight forward.

Thoughts?

2023-09-11 15:45 UTC, yassinkhalifa commented
Yeah, this is much better! I can work on that.

2023-09-11 19:38 UTC, yassinkhalifa commented
I added the suggested function parse_time and made it only return component #0 because we are always interested in  the hours component (the first element) which simplified the check_time part as you indicated and changed the formatting of default_time to just a decimal '1' so that it aligns with the output of parse_time. Please take a look and let me know if I misinterpreted any of your instructions.

2023-09-12 14:46 UTC, djperrefort requested changes
I've highlighted a mix of style and functional suggestions.

2023-09-12 14:46 UTC, djperrefort commented on apps/crc_interactive.py
> +    def parse_time(time_str: str) -> time:
My original suggestion was to define this as a top level function, but your implementation as method is equally valid. The only difference is that this method should be made static if included as a method:

```python
@staticmethod
def parse_time(time_str: str) -> time:
    ...
```

If left as is, the parent class will pass `self` as the first argument, which is not included in the signature (nor should it be in this case).

Leave this class as a method, but add the static tag.

2023-09-12 14:46 UTC, djperrefort commented on apps/crc_interactive.py
> +    def parse_time(time_str: str) -> time:
Neither `time` nor `ArgumentTypeError` has been imported. Add an import statement for each of them:

```python
from argparse import Namespace, ArgumentTypeError
from datetime import time
```

Also the `datetime.datetime` class is no longer needed in the imports.

2023-09-12 14:46 UTC, djperrefort commented on apps/crc_interactive.py
> +    def parse_time(time_str: str) -> time:
Add function docstring with `Args`, `Return`, and `Raises` sections. Here is an automatically generated example:

```python
    """Parse a string representation of time in 'HH:MM:SS' format and return a time object

    Args:
        time_str: A string representing time in 'HH:MM:SS' format.

    Returns:
        time: A time object representing the parsed time.

    Raises:
        ArgumentTypeError: If the input string is not in the correct format or cannot be parsed.
    """
```

2023-09-12 14:46 UTC, djperrefort commented on apps/crc_interactive.py
> +    default_time = '1'  # Default runtime
This needs to be the same object type as used by the parser argument definition. 

```python
default_time = time(1)
```

2023-09-12 14:46 UTC, djperrefort commented on apps/crc_interactive.py
>              help=f'run time in hours or hours:minutes [default: {self.default_time} hour] ')
Minor point, but lets drop the word hour from `[default: {self.default_time} hour]`. I think it reads more nicely with the fstring auto formatting of time objects.

You're welcome to ignore this suggestion if you disagree.

2023-09-12 14:46 UTC, djperrefort commented on apps/crc_interactive.py
> +        check_time = int(args.time)
This type cast does not work. Python cannot automatically cast from time objects to integers. You need to handle hours, minutes, and seconds manually.

```
check_time = args.time.hour + args.time.minute / 60 + args.time.second / 3600
```

2023-09-12 14:46 UTC, djperrefort commented on apps/crc_interactive.py
> +            'time': '--time={}:00:00',
This creates `--time=01:00:00:00:00`. The correct form is `'time': '--time={}'`. Time objects automatically format to strings as `HH:MM:SS`.

2023-09-12 19:21 UTC, yassinkhalifa commented
I went through all the requested changes and completed them. Please let me know if there is anything else I need to change.

2023-09-12 19:38 UTC, djperrefort approved these changes

2023-09-15 13:48 UTC, djperrefort commented
@yassinkhalifa please merge this in when you are ready

2023-09-15 13:55 UTC, merged